@baseUrl = http://localhost:3000

### Get home
GET {{baseUrl}}/

### Get livros
GET {{baseUrl}}/autors

### Get livros
GET {{baseUrl}}/livros/674333c05a8708e65ec1c18c

### POST livros
POST  {{baseUrl}}/autors
Content-Type: application/json

{
    "nome": "spider",
    "nacionalidade": "otro",
}


### PUT livros
PUT {{baseUrl}}/livros/674333c05a8708e65ec1c18c
Content-Type: application/json

{
    "titulo": "mama",
    "editora": "o",
    "preco": 5354,
    "paginas": 5
}


### DELETE livros
DELETE {{baseUrl}}/livros/674333c05a8708e65ec1c18c
Content-Type: application/json

